name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v4
    - name: install
      run: cd gmrender-resurrect
    - name: update
      run: ./autogen.sh
    - name: lib
      run: ./configure
    - name: lib
      run: make

	
